version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fixtur-myreserve-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://fixtur_user:fixtur_pass@postgres:5432/fixtur_db?schema=public
      - JWT_SECRET=fixtur-secret-super-secure-production-jwt-token-change-me
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: fixtur-postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=fixtur_user
      - POSTGRES_PASSWORD=fixtur_pass
      - POSTGRES_DB=fixtur_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fixtur_user -d fixtur_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
